name = "sonson0910/did_contract"
version = "0.1.0"
compiler = "v1.1.21"
plutus = "v3"
description = "DID Management Validator - Face identity on Cardano"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

